### ISSUE TITLE
decommission old OA PubFund link

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/OpenEmory#10]
located here:  https://open.library.emory.edu/publications/oa-fund/proposal/  OR redirect it to the new OA Pub Fund on the new SCO Website here: http://sco.library.emory.edu/open-access-publishing/oa-funding-support/form.html

**Comment by rosy1280** [comment]
Question for Fran: can you enumerate all the places within OE where that link lives?

**Comment by fpici** [comment]
@alexBLR Hi Zo. Since the PT story was created, the link to the re-direct has changed. The new SCO page fund form is located here: http://sco.library.emory.edu/open-access-publishing/oa-funding-support/oa-form.html

**Comment by fpici** [comment]
@rosy1280 I don't believe the link  https://open.library.emory.edu/publications/oa-fund/proposal/ lives anywhere on the OpenEmory site. We cleaned out all instances of it months ago BUT we believe that some users archived the old fund link as a bookmark and have used it instead of going directly to the site where they can access the new form link. This is why Melanie asked that we decommission the old link for those occasional users who use it. Hope this helps,

**Comment by rosy1280** [comment]
- [ ] decommission https://open.library.emory.edu/publications/oa-fund/proposal/ 
- [ ] redirect above link to http://sco.library.emory.edu/open-access-publishing/oa-funding-support/oa-form.html

**Comment by fpici** [comment]
@rosy1280 This ticket is tested and Ready to Deploy."

**Comment by fpici** [comment]
@rosy1280 Hmmmm? I cannot move this into "Ready to Deploy" and I cannot assign you to the ticket?
