### ISSUE TITLE
Ability to view a migrated FileSet in Hyrax and download its files

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#148]
As part of our goal of read-only compatibility, we should confirm that the following Hyrax features function:

- [x] Filesets attached to a work can be viewed
- [ ] Files attached to a FileSet can be downloaded

**Additional Notes:**

As part of working toward getting our migrated data compatible with Hyrax, we may need to ensure that any required metadata is populated on FileSet objects.

Possible tasks:

- Identify minimal required fields that need to be populated to view a FileSet in Hyrax ([probably Hyrax Core metadata](https://github.com/samvera/hyrax/blob/main/app/models/concerns/hyrax/core_metadata.rb))
- Adjust our SOLR/Valkyrie-Fedora fields as needed for FileSet objects

In the below screenshot from Nurax, the minimal fields appear to include

- title
- depositor (for this value, we probably should use something generic like a Hyrax admin account since it was a migration)
- date uploaded
- date created

Characterization data will likely not be populated unless we translate Fedora's binary file metadata to Hyrax SOLR fields. User activity will also likely not be populated because that is generated during the Hyrax ingest process. We also should expect to not have thumbnails.

![Screenshot 2023-06-13 at 4.13.20 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/638b372b-a5c9-4a52-9dd5-88ce714de1e1)

**Comment by abelemlih** [comment]
@eporter23 [PR](https://github.com/emory-libraries/fedora6-hyrax-prototype/pull/9) to add the changes requested above has been approved and merged.

Notes:

- Since we do not use ActiveFedora in this prototype, we do not have the ActiveFedora::Aggregation::ListSource abstraction Hyrax uses to identify file sets attached to a work. I changed the behavior of the prototype to retrieve all file sets attached to a work through field `file_set_ids_ssim`.
- We currently do not support ordering for file sets in Hyrax. @eporter23 and I discussed the ordering functionality for file sets, and determined that it could be addressed in a future ticket. For now, **the prototype assumes ordered members ids are file set ids, which are listed under `file_set_ids_ssim` of a `GenericWork` in Solr.**
- I could not add the ability to download the file associated with a file set. Downloading a file in Hyrax currently relies on ActiveFedora to retrieve the actual file then provide it for download to the user, after checking that they are authorized to see it. Since we do not use ActiveFedora for this prototype, implementing this feature is not feasible within the scope of this prototype. I discussed these limitations with @eporter23.

**Comment by abelemlih** [comment]
@eporter23 new changes have been deployed to Sandbox for testing. You should now be able to view file sets on a work's show page.

**Comment by eporter23** [comment]
@abelemlih looks great! Seeing these in Hyrax has also made me catch a few files that didn't migrate as expected. Depending on how much more Hyrax work we do, I may want us to revisit which dates we choose for date created and date modified (the original upload to Fedora 3 date vs more recent Valkyrie processing dates, etc.) but this can wait pending other priorities.
