### ISSUE TITLE
Adjust SOLRconfig.xml on the server to disable date parsing

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#151]
Look at making this change both in the F6-Blacklight repo as well as on the SOLR side, so we have this in the repo again when we pick it up next.

We anticipate making the changes, restarting, reindexing and testing once done.

**Comment by bwatson78** [comment]
This ticket was generated off of our findings in https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/145.

**Comment by bwatson78** [comment]
I've removed all of the string parsing from the schemaless fields and attempted to reindex. It immediately threw an error of 
```
org.apache.solr.common.SolrException: ERROR: [doc=emory:bsdmn] Error adding field 'lastFixityCheck_tsim'='2022-06-18T04:00:02' msg=Invalid Date String:'2022-06-18T04:00:02'
```
This forced me to dig deeper into how Solr deals with Dates and it seems that the application is highly opinionated with anything it perceives as dates. The parsing methods are actually there to tailor the date strings as they come in to how Solr **needs** them to be parsed. 

This discovery brings us back to a discussion of whether we should update the date formats in the solrcofig.xml to our liking and see if that works. Otherwise, we'll have to mold the date strings when they come into Fedora.

**Comment by eporter23** [comment]
@bwatson78 looks good in SOLR and Blacklight as far as I can see. Moving into Review in case others want to see.
