### ISSUE TITLE
Investigate why FileSet and file attachments fail (Active Fedora)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#187]

**Comment by eporter23** [comment]
This PR may be of interest: https://github.com/samvera/active_fedora/pull/1457

**Comment by bwatson78** [comment]
Error raised:
```
The server managed type (http://www.w3.org/ns/ldp#IndirectContainer) cannot be modified by the client.
```
This is the response back from the LDP gem communicating with the Fedora6 server. The type of error is classified as a `Ldp::Conflict`. Historically (with Fedora 4), Samvera has encountered this error because of `Noid::Rails` minter issues. As far as I can tell, the IndirectContainer error hasn't been documented by Samvera yet.

My best educated guess, since I've seen Lyrasis include documentation that IndirectContainers will be supported in v6.x, is that we don't have some server settings set correctly. My fears, though, are that Lyrasis hasn't broached support for IndirectContainers yet, based upon [this Confluence page](https://wiki.lyrasis.org/display/FF/Fedora+6+Feature+Tracking) from 2+ years ago. I will do more digging in release notes to see if there has been further progress made with this feature. 

It is clear that [this method](https://github.com/samvera/active_fedora/blob/99ac8d1e24bf0ee1673187ae6c0f3456ae9c04c0/lib/active_fedora/associations/indirectly_contains_association.rb#L13) (and its calling class) isn't updated to handle Fedora6 processing. This will now lead me to the link to the PR listed above to see if this addressed by Chris Colvard.
