### ISSUE TITLE
Investigate options to preserve author entries (and their affiliations) in publication order (ActiveFedora)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#200]
In our previous Valkyrie testing, we were able to preserve the original order of authors as listed in the publication in a multi-valued field, but this doesn't currently function when using Hyrax/Bulkrax with ActiveFedora.

There is an open enhancement request in Hyrax regarding this functionality: https://github.com/samvera/hyrax/issues/4781

Author affiliations information:
In OpenEmory's MODS metadata, the authors are stored as complex fields that include affiliations as well as separating first names and last names. The order of entries in the MODS XML replicates the order in the actual publication. We should investigate options for how to replicate this as we move toward Hyrax in the future.

We can also look at work done in ETDs (https://github.com/curationexperts/laevigata) where graduate students' committee members and their affiliations are stored as nested objects in Fedora.

Another example is Curate's Preservation Events, which are nested objects within a work that include multiple properties for each sub-object.

Ideally, we need to store each author as a multi-part entry:
Publication order, Lastname, Firstname, Affiliation

MODS example:

> <mods:name type="personal">
> <mods:namePart type="family">Jung</mods:namePart>
> <mods:namePart type="given">Enjae</mods:namePart>
> mods:role
> <mods:roleTerm type="text">author</mods:roleTerm>
> </mods:role>
> mods:affiliationWashington University School of Medicine</mods:affiliation>
> </mods:name>
> <mods:name type="personal">
> <mods:namePart type="family">Perrone</mods:namePart>
> <mods:namePart type="given">Erin E.</mods:namePart>
> mods:role
> <mods:roleTerm type="text">author</mods:roleTerm>
> </mods:role>
> mods:affiliationDetroit Medical Center</mods:affiliation>
> </mods:name>
> <mods:name type="personal" ID="zliang2">
> mods:role
> <mods:roleTerm type="text">author</mods:roleTerm>
> </mods:role>
> mods:affiliationEmory University</mods:affiliation>
> <mods:namePart type="given">Zhe</mods:namePart>
> <mods:namePart type="family">Liang</mods:namePart>
> </mods:name>
> <mods:name type="personal">
> <mods:namePart type="family">Breed</mods:namePart>
> <mods:namePart type="given">Elise</mods:namePart>
> mods:role
> <mods:roleTerm type="text">author</mods:roleTerm>
> </mods:role>
> mods:affiliationEmory University</mods:affiliation>
> </mods:name>

**Comment by abelemlih** [comment]
@eporter23 The following are the solutions I found, from simplest to most difficult to implement:

### University of Michigan: DeepBlue

https://blogs.lib.umich.edu/library-tech-talk/adding-ordered-metadata-fields-samvera-hyrax

The solution is super simple. They basically added a new text metadata field to store the order encoded in a JSON string. So for creators, there would be a creators_ordered  text field that contains the json of the array of creators stored entirely in string format. The idea is when creators are stored, the entire array is converted into a string json, and stored in that separate field. When a user attempts to view/edit the list, the application checks the ordered field metadata first, if it exists and valid, it returns those values. Otherwise, if there was any encoding issue for instance, it returns the original unordered list of values.

### Oregon State University: ScholarsArchive

https://github.com/osulp/Scholars-Archive

In this solution, to save the ordering of creators for instance, the application saves a field called `nested_ordered_creator_label_ssim` in Solr, which stores the list of creators in the following format: "creator$index". When creators are displayed in the application, they are ordered based on the value of the index stored in that field.


### Valkyrie: Fedora Ordered List

Valkyrie's fedora adapter supports ordered members, using the `OrderedList` model: https://github.com/samvera/valkyrie/blob/7acd4d52eca6305b440f4c1f24b9fef7a6be98e7/lib/valkyrie/persistence/fedora/ordered_list.rb. This is the most advanced and efficient implementation I have found. It is also the most difficult solution to implement, since it will be more difficult to repurpose for Active Fedora and the prototype we are building.

Let me know if you have any questions, and which solution you would like to proceed forward with.
