### ISSUE TITLE
Create instructions for setting up Fedora 6 from OCFL

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/OpenEmory#83]
These instructions should allow new developers to set up a new Fedora 6 instance with a given OCFL directory and see the objects in the Fedora UI.

This work includes
- [x] Creating a zip, tar.gz, or other compressed file containing our current OCFL directory
- [x] Creating or linking to instructions for setting up a dev Fedora 6 server. I think this is pointing to [fcrepo_wrapper](https://github.com/cbeer/fcrepo_wrapper), and explaining where the OCFL data should be unzipped at a minimum.
- [x] Creating or linking to instructions for getting the OCFL objects to show in the Fedora UI. I think this is only reindexing Fedora?

**Comment by eporter23** [comment]
I removed the one embargoed record and the remaining 11 should be fine to share. I'm not sure what happens when "deleting" from Fedora 6 UI, though. These are the PIDs we can share:
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:gjpc5
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:gjs96
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:fj9p7
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:pqpg4
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:dzmbk
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:pqqq6
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:fjktm
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:fm17r
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:gj35k
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:fjhxt
http://10.65.19.21:8080/fcrepo-webapp-6.4.0/rest/emory:q4fd0

**Comment by jcrompton42** [comment]
I couldn't get the fcrepo-wrapper to work for reindexing, but here are instructions for using the one click install functionality from fedora:
https://emorylib.atlassian.net/wiki/spaces/ULTS/pages/31391745/Fedora+6+Dev+Setup

**Comment by tmiles2** [comment]
@rotated8 Can you take a look at this ticket and followup with Beth with any questions?

**Comment by tmiles2** [comment]
Pending a review by Collin.

**Comment by eporter23** [comment]
@rotated8 FYI, if you share the OCFL please note that due to the timing of when we exported this, there are some fileset objects in there in addition to the stock migrated objects.

**Comment by eporter23** [comment]
@rotated8 the original objects I created by hand are still in the OCFL as well, so we may need to do some more cleanup depending on what we want to share - a stock Fedora 3>6 migration only?

**Comment by rotated8** [comment]
@eporter23 Ok, I'll close this ticket in favor of exporting a fresh set when we start working with prod data.
