### ISSUE TITLE
Creating new works - file uploads fail to complete in testopen

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#92]
During testing the week of 3/8, we can start the file upload process but the process fails to complete and eventually returns a blank screen.

Editing existing works is functional.

**Comment by eporter23** [comment]
Resource index backend is indexing, but not responding properly to EUL Fedora via SPARQL queries - Zo and Beth are continuing to investigate.

**Comment by jcrompton42** [comment]
So far we have 

- wiped the oracle db and rebuilt it
- rebuilt the index against a fresh db
- rebuilt the index using a postgresql triplestore backend -it works! But we would have to rewrite most of our legacy codebase libraries because postgres triplestores do not support sparql queries
 
knowing that the issue is with the resource index that is embedded mulgara, we tried 
- creating a standalone mulgara instance
- recompiling mulgara with necessary permissions to run a standalone mulgara instance
- we now have a semi working resource index but it errors on a lot of queries with an umarshal rmi resource exception
I am reasonably certain this is coming from mulgara. I have tried all the classpath fixes recommended by the docs to try to fix it but have still failed. 
I am not super confident in my ability to fix a java project from 2014. 


-

**Comment by rotated8** [comment]
This issue has been resolved!

Our current practice is to run Mulgara a customized version of v2.1.13 (the last version available) as a remote, standalone triplestore on the same server as Fedora 3 QA using Java 6. Additionally, Java needs to run a tool called [RMI](https://docs.oracle.com/en/java/javase/20/rmi/index.html#RMIUG-GUID-70825E99-57CF-470F-871A-5CCB6C2771BE) that (as best we understand) allows Mulgara and Fedora to communicate with each other. RMI is run via `/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/java -Djava.rmi.server.useCodebaseOnly=false -jar mulgara-2.1.13.jar -s fedora -w -r 8000`. Running Mulgara in this way requires the user to delete the index manually before reindexing. In embedded Mulgara, Fedora would do this for us. Once this was in place, the RISearch started working again- searching for something more specific than `* * *` no longer failed.

Temp files (uploaded files) in OE initially did not work. Django was overriding permissions to prevent security issues. OE would try to open the file to generate a MD5 checksum, but was not allowed to. This was fixed by allowing Fedora to calculate the MD5 for the application. Next, PIDMan QA was misconfigured, and the password OE was using was not working. The password was updated on the PIDMan side. Then, OE started throwing errors requesting new PIDs, with PIDMan saying the ID was already in use. The solution was to change the namespace for PIDs from "emory" (as used in production), to "testemory". Additionally, the ID was generated as bytes, rather than a string, so the value needed to be recast.

Now, file uploads are completing as expected, and the correct data is showing up in Fedora.
